{{- range .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations: {{- toYaml .annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: {{ $.Values.container.ports.http }}
---
{{- end }}
