apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.container.ports.http }}
      name: http
  clusterIP: None
  selector:
    app: {{ .Values.name }}
