name: keycloak
replicas: 3
imagePullSecrets: []
container:
  image: quay.io/keycloak/keycloak
  version: latest
  command: ["/opt/keycloak/bin/kc.sh", "start-dev"]
  args: []
  pullPolicy: IfNotPresent
  ports:
    http: 8080
    management: 9000
    infinispan: 7800
  requests:
    memory: 512Mi
    cpu: 500m
  limit:
    memory: 2Gi
    cpu: 2
  env:
    - name: KC_DB
      value: "dev-file"
ingress:
  - name: public
    host: ""
    annotations: {}
  - name: private
    host: ""
    annotations: {}

keycloak-config-cli:
  enabled: false