apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-headless
spec:
  ports:
    - port: {{ .Values.container.ports.infinispan }}
      name: infinispanPort
  clusterIP: None
  selector:
    app: {{ .Values.name }}
